### ISSUE TITLE
Problem in saving and loading request with a JSON body

### ISSUE THREAD

**Issue by abbasmousavi** [buzzfeed/MockDuck#24]
The library uses the body of requests to generate the hash. If you serialize your native models to JSON and use it as the body of the request (which is a common use-case) the order of keys will be random, so the hash can be different when you record the request and when you try to load it. I know that this is the responsibility of the normalizedURL method in the delegate to normalize the requests, but maybe we can find a solution for this inside the library, Because there is no way to "sort" JSON in the request.

My suggestion is to use an algorithm to make a string from JSON (independent of key orders) and using that string to happen to hash data. something like this

```
func sort(dictionary: [String: Any]) -> String {
   let sorted = dictionary.keys.sorted().reduce(“”) { (acc, iteration) -> String in
       if let json = dictionary[iteration] as? [String: Any] {
           return acc.appending(“\(iteration):\(sort(dictionary: json)),“)
       } else {
           return acc.appending(“\(iteration):\(dictionary[iteration]!),“)
       }
   }
   return String(sorted.dropLast())
}
```

**Comment by scelis** [comment]
We have some similar requests that we record using MockDuck, and we just have some basic code in our app that uses [`JSONSerialization.WritingOptions.sortedKeys`](https://developer.apple.com/documentation/foundation/jsonserialization/writingoptions/2888322-sortedkeys) to ensure a consistent JSON body. We only execute this code when MockDuck is actively recording so our app itself doesn't incur a performance hit.

Because it's not super easy to check each and every request for a body that can be decoded to a JSON string, I think the current best-practice recommendation is to do the above in your own request logic.

**Comment by scelis** [comment]
@abbasmousavi How would this approach work for your usecase?

**Comment by abbasmousavi** [comment]
It is a good suggestion. Will test it.

**Comment by nunogoncalves** [comment]
Yeah! We were not aware of `JSONSerialization.WritingOptions.sortedKeys` 😱 Thanks for that! 
We will try to update the body in the normalized method! Without testing, it should work. :)
